--- #YAML:1.0
name:                Digest-Skein
version:             0.03
abstract:            Perl interface to the Skein digest algorithm
license:             gpl
author:              
    - Radoslaw Zielinski <radek@pld-linux.org
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Digest:                        0
    MIME::Base64:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
